### ISSUE TITLE
视频音频加载器

### ISSUE THREAD

**Issue by xiaojue** [xiaojue/EasySlide#1]
独立出来一个loader类，增加音频视频加载和控制。

**Comment by xiaojue** [comment]
这部分在下一个版本中会有体现。

**Comment by cocody** [comment]
都2026了，这个还未出来

**Comment by xiaojue** [comment]
@cocody 本地有一个版本，这几天合上去，之前一直没有更新。几个月前就做完了。。

**Comment by xiaojue** [comment]
@cocody 已经提交新代码，可以在demo中查看music.html 见使用方法。
