### ISSUE TITLE
dome 中 allowSwipe 永远为null?

### ISSUE THREAD

**Issue by cocody** [xiaojue/EasySlide#3]
page.on('slide-switchEnd',function(allowSwipe){
    console.log(allowSwipe); // null
    if (allowSwipe === "no" || allowSwipe === "prev") {
      utils.hide(arrow);
    } else {
      utils.show(arrow);
    }
  });

**Comment by xiaojue** [comment]
![image](https://cloud.githubusercontent.com/assets/289225/12708013/d3df178c-c8d5-11e5-91a9-0e4fe671dfc7.png)
需要自己设置的，这个参数的意义是 当前页是否可以被滑动。你不设置肯定都是null。
